### ISSUE TITLE
waiting for file chooser failed on Github Actions

### ISSUE THREAD

**Issue by naptestdev** [fawazahmed0/youtube-uploader#142]
The problem still persists. I'm using version 1.3.70. Here's my code
```javascript
import { upload } from "youtube-videos-uploader";
import dotenv from "dotenv";
dotenv.config();

const res = await upload(
  {
    email: process.env.EMAIL,
    pass: process.env.PASSWORD,
    recoveryemail: process.env.RECOVERY_EMAIL,
  },
  [
    {
      path: "./video.mp4",
      title: `My test video`,
      description: "Test description",
      language: "english",
      skipProcessingWait: true,
      onProgress: (progress) => console.log("Progress: ", progress),
      onSuccess: (url) => console.log("Uploaded: ", url),
      channelName: "Code Weather Videos",
    },
  ],
  {
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-extensions"],
  }
);

console.log(res);
```

The github actions workflow
```yml
name: Upload video
on:
  workflow_dispatch:
jobs:
  render:
    name: Upload video
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      RECOVERY_EMAIL: ${{ secrets.RECOVERY_EMAIL }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget libgbm-dev
      - run: npm i
      - run: node index.js
```

Here's the error
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/88878684/181588729-5a51b55e-256f-48a7-ac35-c1e3ad77f4e4.png">
